# Generated by Django 4.2.7 on 2025-03-25 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meetingplaner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
